"""Codex emitter: render canonical components into Codex-native artifacts.

Produces (all DETERMINISTIC — sorted enumeration, fixed key order, no timestamps,
no host paths, ``\n``-only with a single trailing newline):

  * ``codex-agents/<name>.toml`` — one per agent (16). ``developer_instructions``
    is the transformed body as a TOML LITERAL ``'''...'''`` multiline string;
    the build FAILS if a body contains ``'''``. ``sandbox_mode`` and
    ``mcp_servers`` derive from the ``tools:`` list.
  * ``plugins/maungs-agentic-toolbelt/skills/<name>/SKILL.md`` (+
    ``agents/openai.yaml``) — one folder per skill, body transformed,
    ``disable-model-invocation`` stripped.
  * ``codex-hooks/hooks.json`` template (``__TOOLBELT_HOOK_DIR__`` placeholder)
    + ``codex-hooks/<name>.sh`` adapted hook bodies.

Pure Python 3 stdlib.
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Tuple

from . import common
from .. import transforms


# ---------------------------------------------------------------------------
# Deterministic serializers
# ---------------------------------------------------------------------------

def toml_literal_block(value: str) -> str:
    """Serialize ``value`` as a TOML literal multiline string (``'''...'''``).

    Literal strings do NO escape processing, so a prompt body survives verbatim.
    FAILS LOUD if the body itself contains ``'''`` (decision 7). The opening
    ``'''`` is followed by a newline (TOML trims the first newline of a multiline
    string), and the body's own ``\n``-only line endings are preserved.
    """
    if "'''" in value:
        raise ValueError(
            "body contains a literal triple-single-quote (''') which cannot be "
            "represented as a TOML literal multiline string"
        )
    # Open on its own line; TOML strips the immediately-following newline.
    return "'''\n" + value + "\n'''"


def toml_string(value: str) -> str:
    """Serialize a single-line TOML basic string with minimal escaping."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return '"' + escaped + '"'


def toml_string_array(values: List[str]) -> str:
    """Serialize a TOML array of basic strings, fixed order (caller pre-sorts)."""
    return "[" + ", ".join(toml_string(v) for v in values) + "]"


def json_dumps(obj) -> str:
    """Deterministic JSON: 2-space indent, keys in the insertion order given.

    We rely on dict insertion order (Python 3.7+) for a declared key sequence;
    callers build dicts in the intended order. ``ensure_ascii=False`` keeps any
    unicode (e.g. the robot marker) intact and byte-stable.
    """
    return json.dumps(obj, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Agent -> TOML
# ---------------------------------------------------------------------------

def render_agent_toml(comp: common.Component) -> str:
    """Render one agent Component to its ``codex-agents/<name>.toml`` text.

    Fixed field order: name, description, sandbox_mode, mcp_servers (omitted when
    no mcp tools), the empty model-override comment block, then
    developer_instructions as the literal body.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    body = transforms.transform_body(comp.body, name)
    sandbox = common.derive_sandbox_mode(comp.tools)
    servers = common.derive_mcp_servers(comp.tools)

    lines: List[str] = []
    lines.append("# Generated by tools/build.py from agents/%s.md — DO NOT EDIT BY HAND." % name)
    lines.append("# Edit the canonical agents/%s.md, then run: python3 tools/build.py --target codex" % name)
    lines.append("")
    lines.append("name = %s" % toml_string(name))
    lines.append("description = %s" % toml_string(description))
    lines.append("sandbox_mode = %s" % toml_string(sandbox))
    if servers:
        lines.append("mcp_servers = %s" % toml_string_array(servers))
    lines.append("")
    lines.append("# model / model_reasoning_effort are omitted by design (model-agnostic).")
    lines.append("# Uncomment + set to pin a model for this agent on your install:")
    lines.append("# model = \"\"")
    lines.append("# model_reasoning_effort = \"\"")
    lines.append("")
    lines.append("developer_instructions = %s" % toml_literal_block(body))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Skill -> transformed SKILL.md (+ agents/openai.yaml)
# ---------------------------------------------------------------------------

def render_skill_md(comp: common.Component) -> str:
    """Render one skill Component to its transformed ``SKILL.md`` text.

    Frontmatter is re-emitted with ``disable-model-invocation`` stripped (Codex
    has no equivalent; every skill sets it false anyway), ``name`` + ``description``
    carried (description transformed), and the transformed body below.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    body = transforms.transform_body(comp.body, name)

    fm: List[str] = ["---", "name: %s" % name, "description: %s" % description, "---"]
    return "\n".join(fm) + "\n\n" + body


def render_skill_openai_yaml(comp: common.Component) -> str:
    """Render the optional ``agents/openai.yaml`` UI-metadata file (decision 13).

    Zero-drift-risk polish: name + a one-line summary derived from the
    (transformed) description's first sentence.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    # First sentence (up to the first period+space or end), trimmed.
    summary = description.split(". ")[0].strip().rstrip(".")
    # YAML-safe: wrap in double quotes, escape embedded quotes + backslashes.
    safe = summary.replace("\\", "\\\\").replace('"', '\\"')
    lines = [
        "# Generated by tools/build.py — DO NOT EDIT BY HAND.",
        "name: %s" % name,
        'summary: "%s"' % safe,
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hooks -> codex-hooks/*.sh + hooks.json
# ---------------------------------------------------------------------------

def render_hook_body(filename: str, body: str) -> str:
    """Adapt one canonical hook ``.sh`` body for Codex.

    Applies the per-hook transform, then the uniform header annotation. The
    ``__TOOLBELT_HOOK_DIR__`` placeholder is NOT inserted into the body (the hook
    scripts resolve their own dir from ``BASH_SOURCE``); the placeholder lives
    only in ``hooks.json``'s ``command`` entries.
    """
    adapted = transforms.transform_hook_body(filename, body)
    # Insert a generated-by note after the shebang line.
    lines = adapted.split("\n")
    if lines and lines[0].startswith("#!"):
        note = [
            lines[0],
            "#",
            "# Generated by tools/build.py from hooks/%s — DO NOT EDIT BY HAND." % filename,
            "# Edit the canonical hooks/%s, then: python3 tools/build.py --target codex" % filename,
        ]
        return "\n".join(note + lines[1:])
    return adapted


def render_hooks_json() -> str:
    """Render the Codex ``hooks.json`` template with the placeholder hook dir.

    Mirrors the canonical event mapping; ``command`` entries point at the
    generated ``codex-hooks/*.sh`` via the ``__TOOLBELT_HOOK_DIR__`` placeholder
    the installer substitutes at install time.
    """
    p = transforms.HOOK_DIR_PLACEHOLDER

    def cmd(script: str) -> str:
        return '"%s"/%s' % (p, script)

    obj = {
        "hooks": {
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {"type": "command", "command": cmd("toolbelt-router.sh"), "timeout": 10}
                    ]
                }
            ],
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {"type": "command", "command": cmd("pretooluse-guard.sh"), "timeout": 10}
                    ],
                },
                {
                    "matcher": "Task|Skill",
                    "hooks": [
                        {"type": "command", "command": cmd("usage-tracker.sh"), "timeout": 10}
                    ],
                },
            ],
            "SessionStart": [
                {
                    "hooks": [
                        {"type": "command", "command": cmd("sessionstart-loader.sh"), "timeout": 10}
                    ]
                }
            ],
        }
    }
    return json_dumps(obj)


# ---------------------------------------------------------------------------
# Full emit: build the {repo-relative path -> content} map
# ---------------------------------------------------------------------------

HOOK_BODY_FILES = [
    "lib-telemetry.sh",
    "pretooluse-guard.sh",
    "sessionstart-loader.sh",
    "toolbelt-router.sh",
    "usage-tracker.sh",
]


def build_artifacts(root: str) -> Dict[str, str]:
    """Return the full {repo-relative path -> finalized content} for the Codex target.

    Deterministic: agents/skills/hooks enumerated sorted; content finalized to a
    single trailing newline. This is the single source the writer and the
    ``--check`` differ both consume.
    """
    artifacts: Dict[str, str] = {}

    # Agents -> codex-agents/<name>.toml
    for comp in common.load_agents(root):
        rel = "codex-agents/%s.toml" % comp.name
        artifacts[rel] = common.finalize_emitted(render_agent_toml(comp))

    # Skills -> plugins/maungs-agentic-toolbelt/skills/<name>/SKILL.md (+ openai.yaml)
    for comp in common.load_skills(root):
        base = "plugins/maungs-agentic-toolbelt/skills/%s" % comp.name
        artifacts["%s/SKILL.md" % base] = common.finalize_emitted(render_skill_md(comp))
        artifacts["%s/agents/openai.yaml" % base] = common.finalize_emitted(
            render_skill_openai_yaml(comp)
        )

    # Hooks -> codex-hooks/<name>.sh + hooks.json
    hook_bodies = common.load_hook_bodies(root)
    for fn in sorted(HOOK_BODY_FILES):
        artifacts["codex-hooks/%s" % fn] = common.finalize_emitted(
            render_hook_body(fn, hook_bodies[fn])
        )
    artifacts["codex-hooks/hooks.json"] = common.finalize_emitted(render_hooks_json())

    return artifacts
