"""Codex emitter: render canonical components into Codex-native artifacts.

Produces (all DETERMINISTIC — sorted enumeration, fixed key order, no timestamps,
no host paths, ``\n``-only with a single trailing newline):

  * ``codex-agents/<name>.toml`` — one per agent (16). ``developer_instructions``
    is the transformed body as a TOML LITERAL ``'''...'''`` multiline string;
    the build FAILS if a body contains ``'''``. ``sandbox_mode`` and
    ``mcp_servers`` derive from the ``tools:`` list.
  * ``plugins/maungs-agentic-toolbelt/skills/<name>/SKILL.md`` (+
    ``agents/openai.yaml``) — one folder per skill, body transformed,
    ``disable-model-invocation`` stripped.
  * ``plugins/maungs-agentic-toolbelt/hooks/hooks.json`` +
    ``plugins/maungs-agentic-toolbelt/hooks/<name>.sh`` adapted hook bodies.
  * bundled helper scripts required by generated skills.

Pure Python 3 stdlib.
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Tuple

from . import common
from .. import transforms


# ---------------------------------------------------------------------------
# Deterministic serializers
# ---------------------------------------------------------------------------

def toml_literal_block(value: str) -> str:
    """Serialize ``value`` as a TOML literal multiline string (``'''...'''``).

    Literal strings do NO escape processing, so a prompt body survives verbatim.
    FAILS LOUD if the body itself contains ``'''`` (decision 7). The opening
    ``'''`` is followed by a newline (TOML trims the first newline of a multiline
    string), and the body's own ``\n``-only line endings are preserved.
    """
    if "'''" in value:
        raise ValueError(
            "body contains a literal triple-single-quote (''') which cannot be "
            "represented as a TOML literal multiline string"
        )
    # Open on its own line; TOML strips the immediately-following newline.
    return "'''\n" + value + "\n'''"


# Named control-char escapes shared by the TOML basic-string + YAML
# double-quoted-scalar paths. Both grammars accept these named escapes AND the
# ``\uXXXX`` form for any other control character, so one escaper is valid for both.
_NAMED_ESCAPES = {
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
}


def escape_controls(value: str) -> str:
    """Escape ``\\`` + ``"`` + every control char for a quoted string.

    Maps backslash and double-quote first, then the named controls
    (``\\b \\t \\n \\f \\r``), then any remaining char with ``ord < 0x20`` or
    ``ord == 0x7f`` as ``\\uXXXX``. The output is valid in BOTH a TOML basic
    string and a YAML double-quoted scalar (BUG-4 + BUG-5), so an unprintable
    byte in a description or body can never produce an unparseable artifact.
    """
    out: List[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch in _NAMED_ESCAPES:
            out.append(_NAMED_ESCAPES[ch])
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def toml_string(value: str) -> str:
    """Serialize a single-line TOML basic string with full control-char escaping."""
    return '"' + escape_controls(value) + '"'


def toml_string_array(values: List[str]) -> str:
    """Serialize a TOML array of basic strings, fixed order (caller pre-sorts)."""
    return "[" + ", ".join(toml_string(v) for v in values) + "]"


def json_dumps(obj) -> str:
    """Deterministic JSON: 2-space indent, keys in the insertion order given.

    We rely on dict insertion order (Python 3.7+) for a declared key sequence;
    callers build dicts in the intended order. ``ensure_ascii=False`` keeps any
    unicode (e.g. the robot marker) intact and byte-stable.
    """
    return json.dumps(obj, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Agent -> TOML
# ---------------------------------------------------------------------------

def render_agent_toml(comp: common.Component) -> str:
    """Render one agent Component to its ``codex-agents/<name>.toml`` text.

    Fixed field order: name, description, sandbox_mode, mcp_servers (omitted when
    no mcp tools), the empty model-override comment block, then
    developer_instructions as the literal body.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    body = transforms.transform_body(comp.body, name)
    sandbox = common.derive_sandbox_mode(comp.tools)
    servers = common.derive_mcp_servers(comp.tools)

    lines: List[str] = []
    lines.append("# Generated by tools/build.py from agents/%s.md — DO NOT EDIT BY HAND." % name)
    lines.append("# Edit the canonical agents/%s.md, then run: python3 tools/build.py --target codex" % name)
    lines.append("")
    lines.append("name = %s" % toml_string(name))
    lines.append("description = %s" % toml_string(description))
    lines.append("sandbox_mode = %s" % toml_string(sandbox))
    if servers:
        lines.append("mcp_servers = %s" % toml_string_array(servers))
    lines.append("")
    lines.append("# model / model_reasoning_effort are omitted by design (model-agnostic).")
    lines.append("# Uncomment + set to pin a model for this agent on your install:")
    lines.append("# model = \"\"")
    lines.append("# model_reasoning_effort = \"\"")
    lines.append("")
    lines.append("developer_instructions = %s" % toml_literal_block(body))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Skill -> transformed SKILL.md (+ agents/openai.yaml)
# ---------------------------------------------------------------------------

def render_skill_md(comp: common.Component) -> str:
    """Render one skill Component to its transformed ``SKILL.md`` text.

    Frontmatter is re-emitted with ``disable-model-invocation`` stripped (Codex
    has no equivalent; every skill sets it false anyway), ``name`` + ``description``
    carried (description transformed), and the transformed body below.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    body = transforms.transform_body(comp.body, name)

    fm: List[str] = ["---", "name: %s" % name, "description: %s" % description, "---"]
    return "\n".join(fm) + "\n\n" + body


def render_skill_openai_yaml(comp: common.Component) -> str:
    """Render the optional ``agents/openai.yaml`` UI-metadata file (decision 13).

    Emit Codex's documented ``interface`` + ``policy`` schema.
    """
    name = comp.name
    description = transforms.transform_description(
        comp.frontmatter.get("description", ""), name
    )
    # First sentence (up to the first period+space or end), trimmed.
    summary = description.split(". ")[0].strip().rstrip(".")
    if len(summary) > 120:
        summary = summary[:117].rstrip() + "..."
    # YAML-safe: wrap in double quotes, escape backslashes + quotes + control
    # chars via the shared escaper (valid in YAML double-quoted scalars too).
    safe = escape_controls(summary)
    display_name = " ".join(part.capitalize() for part in name.split("-"))
    prompt = "Use $%s to help with this task." % name
    lines = [
        "# Generated by tools/build.py — DO NOT EDIT BY HAND.",
        "interface:",
        '  display_name: "%s"' % escape_controls(display_name),
        '  short_description: "%s"' % safe,
        '  default_prompt: "%s"' % escape_controls(prompt),
        "policy:",
        "  allow_implicit_invocation: true",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hooks -> plugin-root hooks/*.sh + hooks.json
# ---------------------------------------------------------------------------

def render_hook_body(filename: str, body: str) -> str:
    """Adapt one canonical hook ``.sh`` body for Codex.

    Applies the per-hook transform, then the uniform header annotation.
    """
    adapted = transforms.transform_hook_body(filename, body)
    # Insert a generated-by note after the shebang line.
    lines = adapted.split("\n")
    if lines and lines[0].startswith("#!"):
        note = [
            lines[0],
            "#",
            "# Generated by tools/build.py from hooks/%s — DO NOT EDIT BY HAND." % filename,
            "# Edit the canonical hooks/%s, then: python3 tools/build.py --target codex" % filename,
        ]
        return "\n".join(note + lines[1:])
    return adapted


def render_hooks_json() -> str:
    """Render plugin-bundled Codex lifecycle hooks."""

    def cmd(script: str) -> str:
        return 'bash "${PLUGIN_ROOT}/hooks/%s"' % script

    obj = {
        "hooks": {
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {"type": "command", "command": cmd("toolbelt-router.sh"), "timeout": 10}
                    ]
                }
            ],
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {"type": "command", "command": cmd("pretooluse-guard.sh"), "timeout": 10}
                    ],
                }
            ],
            "SessionStart": [
                {
                    "hooks": [
                        {"type": "command", "command": cmd("sessionstart-loader.sh"), "timeout": 10}
                    ],
                }
            ],
            "SubagentStart": [
                {
                    "hooks": [
                        {"type": "command", "command": cmd("usage-tracker.sh"), "timeout": 10}
                    ]
                }
            ],
        }
    }
    return json_dumps(obj)


# ---------------------------------------------------------------------------
# Full emit: build the {repo-relative path -> content} map
# ---------------------------------------------------------------------------

def build_artifacts(root: str) -> Dict[str, str]:
    """Return the full {repo-relative path -> finalized content} for the Codex target.

    Deterministic: agents/skills/hooks enumerated sorted; content finalized to a
    single trailing newline. This is the single source the writer and the
    ``--check`` differ both consume.
    """
    artifacts: Dict[str, str] = {}

    # Agents -> codex-agents/<name>.toml
    for comp in common.load_agents(root):
        rel = "codex-agents/%s.toml" % comp.name
        artifacts[rel] = common.finalize_emitted(render_agent_toml(comp))

    # Skills -> plugins/maungs-agentic-toolbelt/skills/<name>/SKILL.md (+ openai.yaml)
    for comp in common.load_skills(root):
        base = "plugins/maungs-agentic-toolbelt/skills/%s" % comp.name
        artifacts["%s/SKILL.md" % base] = common.finalize_emitted(render_skill_md(comp))
        artifacts["%s/agents/openai.yaml" % base] = common.finalize_emitted(
            render_skill_openai_yaml(comp)
        )

    # Hooks -> plugin-root hooks/<name>.sh + hooks.json. The hook BODY set is
    # filesystem-derived (common.load_hook_bodies) so every canonical hook is
    # emitted; the event->hook REGISTRATION in render_hooks_json stays explicit
    # (it intentionally omits lib-telemetry.sh, which is sourced not registered).
    hook_bodies = common.load_hook_bodies(root)
    for fn in sorted(hook_bodies):
        artifacts["plugins/maungs-agentic-toolbelt/hooks/%s" % fn] = common.finalize_emitted(
            render_hook_body(fn, hook_bodies[fn])
        )
    artifacts["plugins/maungs-agentic-toolbelt/hooks/hooks.json"] = common.finalize_emitted(
        render_hooks_json()
    )

    metrics = common.read_text(os.path.join(root, "bin", "toolbelt-metrics.sh"))
    metrics = metrics.replace(
        "${HOME}/.claude/maungs-toolbelt/usage.jsonl",
        "${HOME}/.codex/maungs-toolbelt/usage.jsonl",
    ).replace("`/toolbelt metrics`", "`$toolbelt metrics`")
    artifacts["plugins/maungs-agentic-toolbelt/bin/toolbelt-metrics.sh"] = (
        common.finalize_emitted(metrics)
    )
    artifacts[
        "plugins/maungs-agentic-toolbelt/skills/toolbelt/scripts/toolbelt-metrics.sh"
    ] = common.finalize_emitted(metrics)

    return artifacts
