#!/usr/bin/env bash
#
# Generated by tools/build.py from hooks/lib-telemetry.sh — DO NOT EDIT BY HAND.
# Edit the canonical hooks/lib-telemetry.sh, then: python3 tools/build.py --target codex
#
# lib-telemetry.sh — shared, sourced helper for Maungs-agentic-toolbelt usage
# telemetry. Sourced by the hooks (toolbelt-router.sh, usage-tracker.sh) — it is
# NOT a hook itself and registers nothing.
#
# Records two kinds of events to an append-only JSONL log:
#   - "suggested" — the prompt-router OFFERED a component (UserPromptSubmit)
#   - "invoked"   — an agent/skill actually RAN (PreToolUse on Task / Skill)
# so you can see how often the toolbelt fires and whether suggestions get used.
#
# OPT-IN, off by default. Nothing is written unless the debug flag is set:
#   export MAUNGS_TOOLBELT_DEBUG=on        # record to the JSONL log
#   export MAUNGS_TOOLBELT_DEBUG=verbose   # ALSO echo each event to stderr
#                                          # (visible under `claude --debug`)
# Any other value (or unset) ⇒ completely silent, zero files, zero overhead.
#
# Log location (override with MAUNGS_TOOLBELT_LOG):
#   ~/.codex/maungs-toolbelt/usage.jsonl    — always on your local machine,
#   never inside a project repo. View it with `@toolbelt metrics`.
#
# Fail-safe: every function returns 0 on any error so telemetry can never wedge
# a hook. Requires jq for safe JSON encoding; without jq it silently no-ops.

# True when telemetry should record at all.
tb_debug_on() {
  case "${MAUNGS_TOOLBELT_DEBUG:-off}" in
    on|1|true|yes|verbose) return 0 ;;
    *) return 1 ;;
  esac
}

# True only at the louder "verbose" tier (adds the stderr trace).
tb_debug_verbose() { [ "${MAUNGS_TOOLBELT_DEBUG:-off}" = "verbose" ]; }

# Resolve the log path (env override → default under ~/.codex).
tb_log_path() {
  printf '%s' "${MAUNGS_TOOLBELT_LOG:-${HOME}/.codex/maungs-toolbelt/usage.jsonl}"
}

# tb_append <jsonl-line> — append one record, best-effort. Never fails the hook.
tb_append() {
  [ -n "$1" ] || return 0
  local log dir
  log="$(tb_log_path)"
  dir="$(dirname "$log")"
  mkdir -p "$dir" 2>/dev/null || return 0
  printf '%s\n' "$1" >>"$log" 2>/dev/null || return 0
  tb_debug_verbose && printf '[maungs-toolbelt] %s\n' "$1" >&2
  return 0
}

# UTC ISO-8601 timestamp (portable across macOS/Linux date).
tb_now() { date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || printf '1970-01-01T00:00:00Z'; }
