#!/usr/bin/env bash
#
# Generated by tools/build.py from hooks/usage-tracker.sh — DO NOT EDIT BY HAND.
# Edit the canonical hooks/usage-tracker.sh, then: python3 tools/build.py --target codex
#
# usage-tracker.sh — SubagentStart telemetry for Maungs-agentic-toolbelt.
# Records invocations of this toolbelt's installed custom subagents.

TB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
. "${TB_DIR}/lib-telemetry.sh" 2>/dev/null || exit 0
tb_debug_on || exit 0
command -v jq >/dev/null 2>&1 || exit 0

input="$(cat 2>/dev/null)"; [ -n "$input" ] || exit 0
event="$(printf '%s' "$input" | jq -r '.hook_event_name // empty' 2>/dev/null)"
[ "$event" = "SubagentStart" ] || exit 0
raw="$(printf '%s' "$input" | jq -r '.agent_type // empty' 2>/dev/null)"
case "$raw" in
  architect|bug-catcher-adversary|bug-catcher-rick|code-translator|context-auditor|context-writer|developer|plan-reviewer|pr-reviewer|product-owner|resolution|security-mentor|security-reviewer|test-author|wiki-auditor|wiki-writer) ;;
  *) exit 0 ;;
esac

session="$(printf '%s' "$input" | jq -r '.session_id // empty' 2>/dev/null)"
cwd="$(printf '%s' "$input" | jq -r '.cwd // empty' 2>/dev/null)"
rec="$(jq -nc --arg ts "$(tb_now)" --arg component "$raw"   --arg session "$session" --arg cwd "$cwd"   '{ts:$ts,event:"invoked",kind:"agent",component:$component,raw:$component,session:$session,cwd:$cwd}' 2>/dev/null)"
tb_append "$rec"
exit 0
